# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
# Split data into Train and Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
# Scale the data using standardization
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [6]:
standardized_X_test[0:10,]

array([[-1.10043289,  1.44906692, -1.25816226, -1.17307792],
       [-0.29849799,  1.44906692, -1.14582635, -1.17307792],
       [-1.10043289,  0.7698168 , -1.31433022, -1.17307792],
       [-0.69946544,  1.22265021, -1.25816226, -1.29655981],
       [-0.56580962,  2.35473375, -1.31433022, -1.29655981],
       [ 0.50343691,  0.31698339,  1.26939585,  1.54352358],
       [ 0.77074854, -0.36226673,  0.98855606,  0.67915038],
       [ 1.03806017, -0.13585002,  0.37070852,  0.18522283],
       [ 1.57268344, -0.36226673,  1.2132279 ,  1.04959604],
       [-1.2340887 ,  0.7698168 , -1.2019943 , -0.80263226]])

In [7]:
# Create the object
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)
# Fit the model
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [8]:
# Predict the results of test data
y_pred = perceptron.predict(standardized_X_test)

In [9]:
# Observed results
print(y_test)

[0 0 0 0 0 2 2 1 2 0 2 2 1 1 2 2 1 2 0 1 0 0 2 0 1 1 2 2 0 2]


In [10]:
# Predicted values
print(y_pred)

[0 0 0 0 0 2 2 1 2 0 1 2 1 1 2 2 1 1 0 1 0 0 2 0 1 1 2 2 0 2]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.78      1.00      0.88         7
           2       1.00      0.83      0.91        12

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30

